### ISSUE TITLE
Not compatible with clamav 1.2.0

### ISSUE THREAD

**Issue by micwoj92** [kpcyrd/libredefender#41]
Trying to build (using Arch Linux PKGBUILD with patch for clamav 1.0)
```
==> Starting build()...
   Compiling clamav-rs v0.5.5 (https://github.com/kpcyrd/clamav-rs?branch=clamav-1.0#93b5ddc4)
error[E0004]: non-exhaustive patterns: `cl_engine_field::CL_ENGINE_CACHE_SIZE` not covered
   --> /home/micwoj92/.cargo/git/checkouts/clamav-rs-c584debbcab03daf/93b5ddc/src/engine.rs:447:11
    |
447 |     match field {
    |           ^^^^^ pattern `cl_engine_field::CL_ENGINE_CACHE_SIZE` not covered
    |
note: `cl_engine_field` defined here
   --> /home/micwoj92/pkg/libredefender/src/libredefender-0.6.0/target/release/build/clamav-sys-e936b018e2cdf245/out/bindings.rs:221:5
    |
196 | pub enum cl_engine_field {
    | ------------------------
...
221 |     CL_ENGINE_CACHE_SIZE = 24,
    |     ^^^^^^^^^^^^^^^^^^^^ not covered
    = note: the matched value is of type `cl_engine_field`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
483 ~         cl_engine_field::CL_ENGINE_PE_DUMPCERTS => EngineValueType::U32,
484 ~         cl_engine_field::CL_ENGINE_CACHE_SIZE => todo!(),
    |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `clamav-rs` (lib) due to previous error
==> ERROR: A failure occurred in build().
    Aborting...
```
